return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	branch = "main",
	lazy = false,
	opts = {
		highlight = { enable = true },
		indent = { enable = true },
		autotag = { enable = true },
		ensure_installed = {
			"bash",
			"c",
			"cpp",
			"css",
			"diff",
			"dockerfile",
			"git_config",
			"git_rebase",
			"go",
			"html",
			"javascript",
			"json",
			"json5",
			"jsonc",
			"lua",
			"make",
			"markdown",
			"markdown_inline",
			"python",
			"regex",
			"ruby",
			"rust",
			"scss",
			"sql",
			"toml",
			"tsx",
			"typescript",
			"vimdoc",
			"yaml",
			"gleam",
			"nix",
			"helm",
			"gotmpl",
		},
	},
	config = function(_, opts)
		require("nvim-treesitter").install(opts.ensure_installed)
		require("nvim-treesitter").setup(opts)
	end,
}
